import { PropertiesCalendarData } from "@/app/types/propertyCalendarData";

export const propertiesCalendarData: PropertiesCalendarData = {
  ["wynwood-house"]: {
    ["2023"]: {
      ["12"]: [
        {
          date: "2023-12-01",
          isBooked: true,
          price: 0,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-02",
          isBooked: true,
          price: 0,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-03",
          isBooked: true,
          price: 0,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-04",
          isBooked: true,
          price: 0,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-05",
          isBooked: true,
          price: 0,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-06",
          isBooked: true,
          price: 0,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-07",
          isBooked: true,
          price: 0,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-08",
          isBooked: true,
          price: 0,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-09",
          isBooked: true,
          price: 0,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-10",
          isBooked: false,
          price: 252,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-11",
          isBooked: true,
          price: 0,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-12",
          isBooked: true,
          price: 0,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-13",
          isBooked: true,
          price: 0,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-14",
          isBooked: true,
          price: 0,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-15",
          isBooked: false,
          price: 595,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-16",
          isBooked: false,
          price: 595,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-17",
          isBooked: false,
          price: 237,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-18",
          isBooked: false,
          price: 247,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-19",
          isBooked: false,
          price: 251,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-20",
          isBooked: false,
          price: 256,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-21",
          isBooked: false,
          price: 301,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-22",
          isBooked: false,
          price: 595,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-23",
          isBooked: false,
          price: 652,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-24",
          isBooked: true,
          price: 0,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-25",
          isBooked: true,
          price: 0,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-26",
          isBooked: true,
          price: 0,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-27",
          isBooked: true,
          price: 0,
          minimumDaysStay: 2,
        },
        {
          date: "2023-12-28",
          isBooked: true,
          price: 0,
          minimumDaysStay: 5,
        },
        {
          date: "2023-12-29",
          isBooked: false,
          price: 1118,
          minimumDaysStay: 9,
        },
        {
          date: "2023-12-30",
          isBooked: false,
          price: 1193,
          minimumDaysStay: 7,
        },
        {
          date: "2023-12-31",
          isBooked: false,
          price: 936,
          minimumDaysStay: 2,
        },
      ],
    },
    ["2024"]: {
      ["01"]: [
        {
          date: "2024-01-01",
          isBooked: false,
          price: 800,
          minimumDaysStay: 5,
        },
        {
          date: "2024-01-02",
          isBooked: false,
          price: 800,
          minimumDaysStay: 5,
        },
        {
          date: "2024-01-03",
          isBooked: false,
          price: 395,
          minimumDaysStay: 3,
        },
        {
          date: "2024-01-04",
          isBooked: false,
          price: 641,
          minimumDaysStay: 3,
        },
        {
          date: "2024-01-05",
          isBooked: false,
          price: 867,
          minimumDaysStay: 3,
        },
        {
          date: "2024-01-06",
          isBooked: false,
          price: 891,
          minimumDaysStay: 3,
        },
        {
          date: "2024-01-07",
          isBooked: false,
          price: 662,
          minimumDaysStay: 3,
        },
        {
          date: "2024-01-08",
          isBooked: false,
          price: 373,
          minimumDaysStay: 3,
        },
        {
          date: "2024-01-09",
          isBooked: false,
          price: 352,
          minimumDaysStay: 3,
        },
        {
          date: "2024-01-10",
          isBooked: false,
          price: 377,
          minimumDaysStay: 3,
        },
        {
          date: "2024-01-11",
          isBooked: false,
          price: 659,
          minimumDaysStay: 3,
        },
        {
          date: "2024-01-12",
          isBooked: false,
          price: 899,
          minimumDaysStay: 3,
        },
        {
          date: "2024-01-13",
          isBooked: false,
          price: 938,
          minimumDaysStay: 3,
        },
        {
          date: "2024-01-14",
          isBooked: false,
          price: 663,
          minimumDaysStay: 3,
        },
        {
          date: "2024-01-15",
          isBooked: false,
          price: 377,
          minimumDaysStay: 3,
        },
        {
          date: "2024-01-16",
          isBooked: false,
          price: 354,
          minimumDaysStay: 3,
        },
        {
          date: "2024-01-17",
          isBooked: false,
          price: 372,
          minimumDaysStay: 3,
        },
        {
          date: "2024-01-18",
          isBooked: false,
          price: 647,
          minimumDaysStay: 3,
        },
        {
          date: "2024-01-19",
          isBooked: false,
          price: 895,
          minimumDaysStay: 3,
        },
        {
          date: "2024-01-20",
          isBooked: false,
          price: 920,
          minimumDaysStay: 3,
        },
        {
          date: "2024-01-21",
          isBooked: false,
          price: 673,
          minimumDaysStay: 3,
        },
        {
          date: "2024-01-22",
          isBooked: false,
          price: 384,
          minimumDaysStay: 3,
        },
        {
          date: "2024-01-23",
          isBooked: false,
          price: 363,
          minimumDaysStay: 3,
        },
        {
          date: "2024-01-24",
          isBooked: false,
          price: 386,
          minimumDaysStay: 3,
        },
        {
          date: "2024-01-25",
          isBooked: false,
          price: 664,
          minimumDaysStay: 3,
        },
        {
          date: "2024-01-26",
          isBooked: false,
          price: 920,
          minimumDaysStay: 5,
        },
        {
          date: "2024-01-27",
          isBooked: false,
          price: 946,
          minimumDaysStay: 5,
        },
        {
          date: "2024-01-28",
          isBooked: false,
          price: 710,
          minimumDaysStay: 5,
        },
        {
          date: "2024-01-29",
          isBooked: false,
          price: 420,
          minimumDaysStay: 5,
        },
        {
          date: "2024-01-30",
          isBooked: false,
          price: 399,
          minimumDaysStay: 5,
        },
        {
          date: "2024-01-31",
          isBooked: false,
          price: 417,
          minimumDaysStay: 5,
        },
      ],
      ["02"]: [
        {
          date: "2024-02-01",
          isBooked: false,
          price: 800,
          minimumDaysStay: 5,
        },
        {
          date: "2024-02-02",
          isBooked: false,
          price: 800,
          minimumDaysStay: 5,
        },
        {
          date: "2024-02-03",
          isBooked: false,
          price: 395,
          minimumDaysStay: 3,
        },
        {
          date: "2024-02-04",
          isBooked: false,
          price: 641,
          minimumDaysStay: 3,
        },
        {
          date: "2024-02-05",
          isBooked: false,
          price: 867,
          minimumDaysStay: 3,
        },
        {
          date: "2024-02-06",
          isBooked: false,
          price: 891,
          minimumDaysStay: 3,
        },
        {
          date: "2024-02-07",
          isBooked: false,
          price: 662,
          minimumDaysStay: 3,
        },
        {
          date: "2024-02-08",
          isBooked: false,
          price: 373,
          minimumDaysStay: 3,
        },
        {
          date: "2024-02-09",
          isBooked: false,
          price: 352,
          minimumDaysStay: 3,
        },
        {
          date: "2024-02-10",
          isBooked: false,
          price: 377,
          minimumDaysStay: 3,
        },
        {
          date: "2024-02-11",
          isBooked: false,
          price: 659,
          minimumDaysStay: 3,
        },
        {
          date: "2024-02-12",
          isBooked: false,
          price: 899,
          minimumDaysStay: 3,
        },
        {
          date: "2024-02-13",
          isBooked: false,
          price: 938,
          minimumDaysStay: 3,
        },
        {
          date: "2024-02-14",
          isBooked: false,
          price: 663,
          minimumDaysStay: 3,
        },
        {
          date: "2024-02-15",
          isBooked: false,
          price: 377,
          minimumDaysStay: 3,
        },
        {
          date: "2024-02-16",
          isBooked: false,
          price: 354,
          minimumDaysStay: 3,
        },
        {
          date: "2024-02-17",
          isBooked: false,
          price: 372,
          minimumDaysStay: 3,
        },
        {
          date: "2024-02-18",
          isBooked: false,
          price: 647,
          minimumDaysStay: 3,
        },
        {
          date: "2024-02-19",
          isBooked: false,
          price: 895,
          minimumDaysStay: 3,
        },
        {
          date: "2024-02-20",
          isBooked: false,
          price: 920,
          minimumDaysStay: 3,
        },
        {
          date: "2024-02-21",
          isBooked: false,
          price: 673,
          minimumDaysStay: 3,
        },
        {
          date: "2024-02-22",
          isBooked: false,
          price: 384,
          minimumDaysStay: 3,
        },
        {
          date: "2024-02-23",
          isBooked: false,
          price: 363,
          minimumDaysStay: 3,
        },
        {
          date: "2024-02-24",
          isBooked: false,
          price: 386,
          minimumDaysStay: 3,
        },
        {
          date: "2024-02-25",
          isBooked: false,
          price: 664,
          minimumDaysStay: 3,
        },
        {
          date: "2024-02-26",
          isBooked: false,
          price: 920,
          minimumDaysStay: 5,
        },
        {
          date: "2024-02-27",
          isBooked: false,
          price: 946,
          minimumDaysStay: 5,
        },
        {
          date: "2024-02-28",
          isBooked: false,
          price: 710,
          minimumDaysStay: 5,
        },
        {
          date: "2024-02-29",
          isBooked: false,
          price: 420,
          minimumDaysStay: 5,
        },
      ],
      ["03"]: [
        {
          date: "2024-03-01",
          isBooked: false,
          price: 800,
          minimumDaysStay: 5,
        },
        {
          date: "2024-03-02",
          isBooked: false,
          price: 800,
          minimumDaysStay: 5,
        },
        {
          date: "2024-03-03",
          isBooked: false,
          price: 395,
          minimumDaysStay: 3,
        },
        {
          date: "2024-03-04",
          isBooked: false,
          price: 641,
          minimumDaysStay: 3,
        },
        {
          date: "2024-03-05",
          isBooked: false,
          price: 867,
          minimumDaysStay: 3,
        },
        {
          date: "2024-03-06",
          isBooked: false,
          price: 891,
          minimumDaysStay: 3,
        },
        {
          date: "2024-03-07",
          isBooked: false,
          price: 662,
          minimumDaysStay: 3,
        },
        {
          date: "2024-03-08",
          isBooked: false,
          price: 373,
          minimumDaysStay: 3,
        },
        {
          date: "2024-03-09",
          isBooked: false,
          price: 352,
          minimumDaysStay: 3,
        },
        {
          date: "2024-03-10",
          isBooked: false,
          price: 377,
          minimumDaysStay: 3,
        },
        {
          date: "2024-03-11",
          isBooked: false,
          price: 659,
          minimumDaysStay: 3,
        },
        {
          date: "2024-03-12",
          isBooked: false,
          price: 899,
          minimumDaysStay: 3,
        },
        {
          date: "2024-03-13",
          isBooked: false,
          price: 938,
          minimumDaysStay: 3,
        },
        {
          date: "2024-03-14",
          isBooked: false,
          price: 663,
          minimumDaysStay: 3,
        },
        {
          date: "2024-03-15",
          isBooked: false,
          price: 377,
          minimumDaysStay: 3,
        },
        {
          date: "2024-03-16",
          isBooked: false,
          price: 354,
          minimumDaysStay: 3,
        },
        {
          date: "2024-03-17",
          isBooked: false,
          price: 372,
          minimumDaysStay: 3,
        },
        {
          date: "2024-03-18",
          isBooked: false,
          price: 647,
          minimumDaysStay: 3,
        },
        {
          date: "2024-03-19",
          isBooked: false,
          price: 895,
          minimumDaysStay: 3,
        },
        {
          date: "2024-03-20",
          isBooked: false,
          price: 920,
          minimumDaysStay: 3,
        },
        {
          date: "2024-03-21",
          isBooked: false,
          price: 673,
          minimumDaysStay: 3,
        },
        {
          date: "2024-03-22",
          isBooked: false,
          price: 384,
          minimumDaysStay: 3,
        },
        {
          date: "2024-03-23",
          isBooked: false,
          price: 363,
          minimumDaysStay: 3,
        },
        {
          date: "2024-03-24",
          isBooked: false,
          price: 386,
          minimumDaysStay: 3,
        },
        {
          date: "2024-03-25",
          isBooked: false,
          price: 664,
          minimumDaysStay: 3,
        },
        {
          date: "2024-03-26",
          isBooked: false,
          price: 920,
          minimumDaysStay: 5,
        },
        {
          date: "2024-03-27",
          isBooked: false,
          price: 946,
          minimumDaysStay: 5,
        },
        {
          date: "2024-03-28",
          isBooked: false,
          price: 710,
          minimumDaysStay: 5,
        },
        {
          date: "2024-03-29",
          isBooked: false,
          price: 420,
          minimumDaysStay: 5,
        },
        {
          date: "2024-03-30",
          isBooked: false,
          price: 399,
          minimumDaysStay: 5,
        },
        {
          date: "2024-03-31",
          isBooked: false,
          price: 417,
          minimumDaysStay: 5,
        },
      ],
    },
  },
};
